apiVersion: v1
kind: ServiceAccount
metadata:
  name: thalos-prime
  namespace: thalos-prime
  labels:
    app: thalos-prime
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: thalos-prime
  namespace: thalos-prime
  labels:
    app: thalos-prime
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: thalos-prime
  namespace: thalos-prime
  labels:
    app: thalos-prime
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: thalos-prime
subjects:
- kind: ServiceAccount
  name: thalos-prime
  namespace: thalos-prime
